# fly.toml app configuration file generated for aml-phonebook-frontend on 2024-02-22T09:23:07-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'aml-phonebook-frontend'
primary_region = 'bog'

[env]
  VITE_BACKEND = 'https://fullstackopen-helsinky-part3-backend.fly.dev/api/persons'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
